### ISSUE TITLE
Runaway scroll to bottom

### ISSUE THREAD

**Issue by akbertram** [skobes/ScrollAnchoring#1]
Upgrade to Chrome 56 broke part of our web application. When the user scrolls with the wheel or by clicking on the scroll bar down, the page scrolls all the way to the bottom.

The web application is handling the scroll event to change the layout of an element from relative to absolute so that it stays visible on the side of the page as the user scrolls down.

Working around this by adding scroll-anchor: none to the scroll container solves the problem.

This appears to be the same issue as here:
https://github.com/angular-ui/ui-scroll/issues/138

If it would be helpful, I can set up a test login for you.

**Comment by skobes** [comment]
Thanks for the report.  We've seen runaway scroll issues in virtual table scrollers that change the "identity" of an element by swapping new content into it (e.g. http://crbug.com/670670) - this tricks Chrome into thinking content has shifted when it hasn't.

In general changing an element from relative to absolute should not be a problem.  If you can attach a test case that demonstrates the issue in your app, I will look into it further.

**Comment by akbertram** [comment]
I took another look at the [code](https://github.com/bedatadriven/activityinfo/blob/bd26b54ac7d0834557b7cf9a0f90b4696065ffc0/ui/app2/src/main/java/org/activityinfo/ui/client/component/formdesigner/FormDesignerPanel.java#L260) behind this page and it's actually a bit hacky.

It looks like scroll event is sunk, and the event handler updates a "spacer" div to push the right hand column further down the page. 

Here is a minimal reproducible example:
https://jsfiddle.net/9e84fs9v/2/

**Comment by skobes** [comment]
Yeah that would do it.  If you push the columns down with margin-top instead, it will work: https://jsfiddle.net/ystr7bgb/2/  (Or disable anchoring with overflow-anchor: none.)

Unfortunately we can't really distinguish "growing a spacer div to make an element stick" from "something offscreen got bigger for some other reason", and adjusting for the latter is the intended purpose of scroll anchoring.  So there will be some edge cases that trigger feedback loops like this.

**Comment by akbertram** [comment]
That seems reasonable. We've pushed out a hotfix  using the overflow-anchor property so we're good.
